---
# Example keys
airflow_fernet_key: xKy13nPFfDflJ0DYGVTwf_DEmbItfURHlEDxrt-bBQw=
airflow_webserver_secret_key: "ihadsf908auw0340684"

airflow_required_python_packages:
  - { name: SQLAlchemy, version: 1.3.23 }
  - { name: psycopg2 }

airflow_extra_packages:
  - celery
  - cgroups
  - ftp
  - http
  - jdbc
  - sftp
  - ssh
